name: Setup ClickHouse VPS
on: workflow_dispatch

jobs:

  iptables:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Setup iptables
        run: sh ./iptables.sh

  clickhouse:
    runs-on: self-hosted
    needs: [iptables]
    steps:
      - uses: actions/checkout@v3
      - name: Install ClickHouse
        run: |
          sh ./clickhouse.sh

  ch_user:
    runs-on: self-hosted
    needs: [clickhouse]
    steps:
      - uses: actions/checkout@v3
      - name: Add User to ClickHouse
        env:
          CH_USR: ${{ secrets.CH_USR }}
          CH_PWD: ${{ secrets.CH_PWD }}
        run: |
          clickhouse-client --query="create user $CH_USR identified with sha256_password by '$CH_PWD'"
          clickhouse-client --query="grant all on * to $CH_USR"

  tools:
    runs-on: self-hosted
    needs: [clickhouse]
    steps:
      - uses: actions/checkout@v3
      - name: Install tools
        run: sh ./tools.sh

  docker:
    runs-on: ubuntu-latest
    needs: [tools]
    steps:
      - uses: actions/checkout@v3
      - name: Install Docker
        run: sh ./docker.sh
